### ISSUE TITLE
[기능추가] 게임이 끝난 후 이전에 배팅했던 금액은 default bet 금액

### ISSUE THREAD

**Issue by coMkkyu** [coMkkyu/spring-web#10]
게임이 끝난 후 이전에 배팅했던 금액이 default bet 금액이어야 한다.

**Comment by dbwjd1094** [comment]
게임이 끝난 후 이전에 배팅했던 금액을 default bet 금액이 되게 설정해줌

**Comment by coMkkyu** [comment]
Available Funds 부분에서 이전에 배팅했던 금액(default bet) 만큼 차감된 금액이 표시되어야 하는데 전체금액이 표시됩니다!! 해결해주세용
